// Groups the dropdown by continent. Not derived from the country data itself
// (Natural Earth's CONTINENT field isn't carried through the build
// pipeline), so this is a plain manual lookup — stable, well-known
// information that doesn't need a data source. A few transcontinental cases
// are resolved to match common convention: Russia and Cyprus as Europe,
// Turkey/Georgia/Armenia/Azerbaijan/Kazakhstan as Asia, Egypt as Africa.
export const CONTINENT_ORDER = ['Africa', 'Asia', 'Europe', 'North America', 'Oceania', 'South America'] as const

export type Continent = (typeof CONTINENT_ORDER)[number]

const AFRICA: readonly string[] = [
  'Algeria',
  'Angola',
  'Benin',
  'Botswana',
  'Burkina Faso',
  'Burundi',
  'Cameroon',
  'Cape Verde',
  'Central African Republic',
  'Chad',
  'Comoros',
  'Democratic Republic of the Congo',
  'Djibouti',
  'Egypt',
  'Equatorial Guinea',
  'Eritrea',
  'Eswatini',
  'Ethiopia',
  'Gabon',
  'Gambia',
  'Ghana',
  'Guinea',
  'Guinea-Bissau',
  'Ivory Coast',
  'Kenya',
  'Lesotho',
  'Liberia',
  'Libya',
  'Madagascar',
  'Malawi',
  'Mali',
  'Mauritania',
  'Mauritius',
  'Mayotte',
  'Morocco',
  'Mozambique',
  'Namibia',
  'Niger',
  'Nigeria',
  'Republic of the Congo',
  'Réunion',
  'Rwanda',
  'Saint Helena, Ascension and Tristan da Cunha',
  'São Tomé and Príncipe',
  'Senegal',
  'Seychelles',
  'Sierra Leone',
  'Somalia',
  'South Africa',
  'South Sudan',
  'Sudan',
  'Tanzania',
  'Togo',
  'Tunisia',
  'Uganda',
  'Zambia',
  'Zimbabwe',
]

const ASIA: readonly string[] = [
  'Afghanistan',
  'Armenia',
  'Azerbaijan',
  'Bahrain',
  'Bangladesh',
  'Bhutan',
  'Brunei',
  'Cambodia',
  'China',
  'East Timor',
  'Georgia',
  'Hong Kong',
  'India',
  'Indonesia',
  'Iran',
  'Iraq',
  'Israel',
  'Japan',
  'Jordan',
  'Kazakhstan',
  'Kuwait',
  'Kyrgyzstan',
  'Laos',
  'Lebanon',
  'Macau',
  'Malaysia',
  'Maldives',
  'Mongolia',
  'Myanmar',
  'Nepal',
  'North Korea',
  'Oman',
  'Pakistan',
  'Palestine',
  'Philippines',
  'Qatar',
  'Saudi Arabia',
  'Singapore',
  'South Korea',
  'Sri Lanka',
  'Syria',
  'Taiwan',
  'Tajikistan',
  'Thailand',
  'Turkey',
  'Turkmenistan',
  'United Arab Emirates',
  'Uzbekistan',
  'Vietnam',
  'Yemen',
]

const EUROPE: readonly string[] = [
  'Albania',
  'Andorra',
  'Austria',
  'Belarus',
  'Belgium',
  'Bosnia and Herzegovina',
  'Bulgaria',
  'Croatia',
  'Cyprus',
  'Czech Republic',
  'Denmark',
  'Estonia',
  'Faroe Islands',
  'Finland',
  'France',
  'Germany',
  'Gibraltar',
  'Greece',
  'Guernsey',
  'Hungary',
  'Iceland',
  'Ireland',
  'Isle of Man',
  'Italy',
  'Jersey',
  'Kosovo',
  'Latvia',
  'Liechtenstein',
  'Lithuania',
  'Luxembourg',
  'Malta',
  'Moldova',
  'Monaco',
  'Montenegro',
  'Netherlands',
  'North Macedonia',
  'Norway',
  'Poland',
  'Portugal',
  'Romania',
  'Russia',
  'San Marino',
  'Serbia',
  'Slovakia',
  'Slovenia',
  'Spain',
  'Svalbard and Jan Mayen',
  'Sweden',
  'Switzerland',
  'Ukraine',
  'United Kingdom',
  'Vatican City',
]

const NORTH_AMERICA: readonly string[] = [
  'Anguilla',
  'Antigua and Barbuda',
  'Aruba',
  'Bahamas',
  'Barbados',
  'Belize',
  'Bermuda',
  'British Virgin Islands',
  'Canada',
  'Caribbean Netherlands',
  'Cayman Islands',
  'Costa Rica',
  'Cuba',
  'Curaçao',
  'Dominica',
  'Dominican Republic',
  'El Salvador',
  'Greenland',
  'Grenada',
  'Guadeloupe',
  'Guatemala',
  'Haiti',
  'Honduras',
  'Jamaica',
  'Martinique',
  'Mexico',
  'Montserrat',
  'Nicaragua',
  'Panama',
  'Puerto Rico',
  'Saint Barthélemy',
  'Saint Kitts and Nevis',
  'Saint Lucia',
  'Saint Martin',
  'Saint Pierre and Miquelon',
  'Saint Vincent and the Grenadines',
  'Sint Maarten',
  'Trinidad and Tobago',
  'Turks and Caicos Islands',
  'U.S. Virgin Islands',
  'United States of America',
]

const OCEANIA: readonly string[] = [
  'American Samoa',
  'Australia',
  'Christmas Island',
  'Cocos (Keeling) Islands',
  'Cook Islands',
  'Federated States of Micronesia',
  'Fiji',
  'French Polynesia',
  'Guam',
  'Kiribati',
  'Marshall Islands',
  'Nauru',
  'New Caledonia',
  'New Zealand',
  'Niue',
  'Norfolk Island',
  'Northern Mariana Islands',
  'Palau',
  'Papua New Guinea',
  'Pitcairn Islands',
  'Samoa',
  'Solomon Islands',
  'Tokelau',
  'Tonga',
  'Tuvalu',
  'Vanuatu',
  'Wallis and Futuna',
]

const SOUTH_AMERICA: readonly string[] = [
  'Argentina',
  'Bolivia',
  'Brazil',
  'Chile',
  'Colombia',
  'Ecuador',
  'Falkland Islands',
  'French Guiana',
  'Guyana',
  'Paraguay',
  'Peru',
  'Suriname',
  'Uruguay',
  'Venezuela',
]

const GROUPS: Record<Continent, readonly string[]> = {
  Africa: AFRICA,
  Asia: ASIA,
  Europe: EUROPE,
  'North America': NORTH_AMERICA,
  Oceania: OCEANIA,
  'South America': SOUTH_AMERICA,
}

export const CONTINENT_BY_COUNTRY: Record<string, Continent> = Object.fromEntries(
  CONTINENT_ORDER.flatMap((continent) => GROUPS[continent].map((name) => [name, continent])),
)
